language: go
install: make get-deps
go:
- 1.6
- tip
notifications:
  slack:
    rooms:
      secure: hVfQtDcXGNSPuAPoIFkJkIbtuNBgAMRpDMAGIL8zV4tAl0oUPZ/pF86ZGvzqBB5m/RzWm46nykPGuq03wWBqhGPFGBq7EnEvNKyQBdtAwi6K7h5de7T8/8ElLUa+P8H7xhhL4vQRLqeiESwsIBj7D2falTem+MKauuo/ffYoxCOJIBEccVMeWFhBq1cB3SZFvwtflCeO7+uD5TTcqmVZK6oJIWCaI4eXi3frWhQru1mvdmv+l8K7Yx5vbPsV3dBuwqzuDpSBKEeAxmYgCvkLKfRdqO+3UfToXXrvJc014yU6jefr5h6JQEnuDI8oOQlfhi2NMUILn93/TMlB2PXSKNUMdzb9lV4VhZKkSU4J797ABDOjhQeyrx/bQSEPefslXoVizQEIA33B3zlzUVtgwE3QE+uQWK4ylGdjp4z41lXGJIpuT7ZbBv6OhTMpDMswO1D9M7X3BPpdz1Iv4aX+YMqMGju8nnwcZAR85xKaCrMcaU7unrdJz5x49KC5kemi6A9RTfB7hm96i2nrthbu9I9FfHprXS8M1Lekq6Y7vXOAJTM+gcWJDru5gko5K3rwbHkVhMs27dqDAbZq1LKGrNS88Aqv1mnh7tDDpmO7Po1zaWcp+N1llyoQxqyN2jIUKcGh2oti85NIBHoq5G49aG2s8ugrfjiWOslB+jB79xE=
